id: P004384
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG16157
  title: ཚད་མ་རིགས་རྒྱན།
  author: ''
  volumes:
    cd2d514232764e198da23c1a58c94161:
      image_group_id: I1KG16175
      title: ''
      volume_number: 1
      total_pages: 458
